# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitlab.com/py_specs/py_specs.git'
platform :ios, '8.0'

target 'PYPrivacyKitDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PYPrivacyKitDemo

  pod 'PYAuthorizedKit',:path => '../'

  target 'PYPrivacyKitDemoTests' do
    inherit! :search_paths
    # Pods for testing
#     pod 'PYPrivacyKit',:path => '../'
  end

  target 'PYPrivacyKitDemoUITests' do
    inherit! :search_paths
    # Pods for testing
#     pod 'PYPrivacyKit',:path => '../'
  end

end
